-- ---------------------------------------------------------------------
-- CARDDB - STORAGE OBJECTS FOR THE CARD SERVICING MODULE (CARDSVC)
-- DB2 FOR Z/OS
-- ---------------------------------------------------------------------

CREATE STOGROUP SGCARD
    VOLUMES ("*")
    VCAT DB2CARD;

CREATE DATABASE CARDDB
    STOGROUP SGCARD
    BUFFERPOOL BP1
    INDEXBP    BP2
    CCSID EBCDIC;

-- Master data ---------------------------------------------------------
CREATE TABLESPACE TSACCT IN CARDDB
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720
    SEGSIZE 32 LOCKSIZE PAGE BUFFERPOOL BP1
    CCSID EBCDIC;

CREATE TABLESPACE TSCARD IN CARDDB
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720
    SEGSIZE 32 LOCKSIZE PAGE BUFFERPOOL BP1
    CCSID EBCDIC;

CREATE TABLESPACE TSLIMIT IN CARDDB
    USING STOGROUP SGCARD PRIQTY 2880 SECQTY 720
    SEGSIZE 16 LOCKSIZE PAGE BUFFERPOOL BP1
    CCSID EBCDIC;

-- High volume transactional -------------------------------------------
CREATE TABLESPACE TSAUTH IN CARDDB
    USING STOGROUP SGCARD PRIQTY 72000 SECQTY 7200
    NUMPARTS 8
    LOCKSIZE ROW LOCKMAX SYSTEM BUFFERPOOL BP2
    CCSID EBCDIC;

CREATE TABLESPACE TSTRAN IN CARDDB
    USING STOGROUP SGCARD PRIQTY 72000 SECQTY 7200
    NUMPARTS 12
    LOCKSIZE ROW LOCKMAX SYSTEM BUFFERPOOL BP2
    CCSID EBCDIC;

CREATE TABLESPACE TSGL IN CARDDB
    USING STOGROUP SGCARD PRIQTY 14400 SECQTY 1440
    SEGSIZE 64 LOCKSIZE PAGE BUFFERPOOL BP2
    CCSID EBCDIC;

CREATE TABLESPACE TSSTMT IN CARDDB
    USING STOGROUP SGCARD PRIQTY 14400 SECQTY 1440
    SEGSIZE 64 LOCKSIZE PAGE BUFFERPOOL BP2
    CCSID EBCDIC;

CREATE TABLESPACE TSDISP IN CARDDB
    USING STOGROUP SGCARD PRIQTY 2880 SECQTY 720
    SEGSIZE 16 LOCKSIZE PAGE BUFFERPOOL BP1
    CCSID EBCDIC;

-- Reference and control -----------------------------------------------
CREATE TABLESPACE TSREF IN CARDDB
    USING STOGROUP SGCARD PRIQTY 1440 SECQTY 360
    SEGSIZE 8 LOCKSIZE PAGE BUFFERPOOL BP0
    CCSID EBCDIC;

CREATE TABLESPACE TSCTRL IN CARDDB
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360
    SEGSIZE 4 LOCKSIZE PAGE BUFFERPOOL BP0
    CCSID EBCDIC;
