-- ---------------------------------------------------------------------
-- PARTYDB - STORAGE OBJECTS FOR THE PARTY / KYC / RISK MODULE
-- SEPARATE STOGROUP AND DATABASE FROM CARDDB.
-- ---------------------------------------------------------------------

CREATE STOGROUP SGPARTY
    VOLUMES ("*")
    VCAT DB2PRTY;

CREATE DATABASE PARTYDB
    STOGROUP SGPARTY
    BUFFERPOOL BP3
    INDEXBP    BP4
    CCSID EBCDIC;

CREATE TABLESPACE TSCUST IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 7200 SECQTY 720
    SEGSIZE 32 LOCKSIZE PAGE BUFFERPOOL BP3
    CCSID EBCDIC;

CREATE TABLESPACE TSKYC IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 2880 SECQTY 720
    SEGSIZE 16 LOCKSIZE PAGE BUFFERPOOL BP3
    CCSID EBCDIC;

CREATE TABLESPACE TSSANC IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 2880 SECQTY 720
    SEGSIZE 16 LOCKSIZE PAGE BUFFERPOOL BP3
    CCSID EBCDIC;

CREATE TABLESPACE TSEXPO IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 14400 SECQTY 1440
    SEGSIZE 32 LOCKSIZE ROW BUFFERPOOL BP4
    CCSID EBCDIC;

CREATE TABLESPACE TSSCORE IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 14400 SECQTY 1440
    SEGSIZE 32 LOCKSIZE ROW BUFFERPOOL BP4
    CCSID EBCDIC;

CREATE TABLESPACE TSRAUD IN PARTYDB
    USING STOGROUP SGPARTY PRIQTY 28800 SECQTY 2880
    SEGSIZE 64 LOCKSIZE PAGE BUFFERPOOL BP4
    CCSID EBCDIC;
