-- ---------------------------------------------------------------------
-- INDEXES - CARDDB AND PARTYDB
-- ---------------------------------------------------------------------

-- CARDDB --------------------------------------------------------------
CREATE UNIQUE INDEX CARDSVC.XACCT01 ON CARDSVC.ACCOUNT (ACCT_ID ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2 CLUSTER;

CREATE INDEX CARDSVC.XACCT02 ON CARDSVC.ACCOUNT (CUST_ID ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2;

CREATE INDEX CARDSVC.XACCT03 ON CARDSVC.ACCOUNT (PARTY_ID ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2;

CREATE INDEX CARDSVC.XACCT04 ON CARDSVC.ACCOUNT
    (NEXT_CYCLE_DATE ASC, ACCT_STATUS ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2;

CREATE UNIQUE INDEX CARDSVC.XCARD01 ON CARDSVC.CARD (CARD_NUM ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2 CLUSTER;

CREATE INDEX CARDSVC.XCARD02 ON CARDSVC.CARD (ACCT_ID ASC, CARD_STATUS ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2;

CREATE INDEX CARDSVC.XCARD03 ON CARDSVC.CARD (CUST_ID ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2;

CREATE UNIQUE INDEX CARDSVC.XLIMIT01 ON CARDSVC.CARD_LIMIT
    (CARD_NUM ASC, LIMIT_TYPE ASC, EFF_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2 CLUSTER;

CREATE UNIQUE INDEX CARDSVC.XAUTH01 ON CARDSVC.AUTHORIZATION
    (AUTH_DATE ASC, CARD_NUM ASC, AUTH_SEQ_NUM ASC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2
    CLUSTER
    PARTITION BY RANGE
      (PARTITION 1 ENDING AT ('2024-03-31'),
       PARTITION 2 ENDING AT ('2024-06-30'),
       PARTITION 3 ENDING AT ('2024-09-30'),
       PARTITION 4 ENDING AT ('2024-12-31'),
       PARTITION 5 ENDING AT ('2025-03-31'),
       PARTITION 6 ENDING AT ('2025-06-30'),
       PARTITION 7 ENDING AT ('2025-09-30'),
       PARTITION 8 ENDING AT ('9999-12-31'));

CREATE INDEX CARDSVC.XAUTH02 ON CARDSVC.AUTHORIZATION
    (ACCT_ID ASC, AUTH_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2;

CREATE INDEX CARDSVC.XAUTH03 ON CARDSVC.AUTHORIZATION
    (POSTED_FLG ASC, AUTH_DATE ASC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2;

CREATE UNIQUE INDEX CARDSVC.XTRAN01 ON CARDSVC.TRANSACTION
    (POST_DATE ASC, TXN_ID ASC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2 CLUSTER;

CREATE INDEX CARDSVC.XTRAN02 ON CARDSVC.TRANSACTION
    (ACCT_ID ASC, POST_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2;

CREATE INDEX CARDSVC.XTRAN03 ON CARDSVC.TRANSACTION
    (CYCLE_ID ASC, GL_POSTED_FLG ASC)
    USING STOGROUP SGCARD PRIQTY 7200 SECQTY 720 BUFFERPOOL BP2;

CREATE UNIQUE INDEX CARDSVC.XMERCH01 ON CARDSVC.MERCHANT (MERCHANT_ID ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0 CLUSTER;

CREATE INDEX CARDSVC.XMERCH02 ON CARDSVC.MERCHANT (MCC ASC, COUNTRY_CD ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0;

CREATE UNIQUE INDEX CARDSVC.XFEE01 ON CARDSVC.FEE_SCHEDULE
    (PRODUCT_CD ASC, FEE_TYPE ASC, EFF_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0 CLUSTER;

CREATE UNIQUE INDEX CARDSVC.XFRAUD01 ON CARDSVC.FRAUD_RULE (RULE_ID ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0 CLUSTER;

CREATE INDEX CARDSVC.XFRAUD02 ON CARDSVC.FRAUD_RULE
    (RULE_CLASS ASC, RULE_SEQ ASC, ACTIVE_FLG ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0;

CREATE UNIQUE INDEX CARDSVC.XRWRD01 ON CARDSVC.REWARDS
    (ACCT_ID ASC, CYCLE_DATE DESC, PROGRAM_CD ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP2 CLUSTER;

CREATE UNIQUE INDEX CARDSVC.XGL01 ON CARDSVC.GL_POSTING
    (GL_BATCH_ID ASC, GL_SEQ_NUM ASC)
    USING STOGROUP SGCARD PRIQTY 1440 SECQTY 720 BUFFERPOOL BP2 CLUSTER;

CREATE INDEX CARDSVC.XGL02 ON CARDSVC.GL_POSTING
    (POST_DATE ASC, GL_ACCOUNT ASC)
    USING STOGROUP SGCARD PRIQTY 1440 SECQTY 720 BUFFERPOOL BP2;

CREATE UNIQUE INDEX CARDSVC.XSTMT01 ON CARDSVC.STATEMENT
    (ACCT_ID ASC, CYCLE_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 1440 SECQTY 720 BUFFERPOOL BP2 CLUSTER;

CREATE UNIQUE INDEX CARDSVC.XDISP01 ON CARDSVC.DISPUTE (DISPUTE_ID ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP1 CLUSTER;

CREATE INDEX CARDSVC.XDISP02 ON CARDSVC.DISPUTE
    (ACCT_ID ASC, STATUS ASC, RAISED_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP1;

CREATE UNIQUE INDEX CARDSVC.XROUTE01 ON CARDSVC.PGM_ROUTE
    (ROUTE_TYPE ASC, ROUTE_KEY ASC, SEQ_NBR ASC, EFF_DATE DESC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0 CLUSTER;

CREATE INDEX CARDSVC.XROUTE02 ON CARDSVC.PGM_ROUTE
    (ACTIVE_FLG ASC, ROUTE_TYPE ASC)
    USING STOGROUP SGCARD PRIQTY 360 SECQTY 180 BUFFERPOOL BP0;

CREATE INDEX CARDSVC.XRTAUD01 ON CARDSVC.ROUTE_AUDIT
    (CORREL_ID ASC, AUDIT_TS ASC)
    USING STOGROUP SGCARD PRIQTY 720 SECQTY 360 BUFFERPOOL BP0;

-- PARTYDB -------------------------------------------------------------
CREATE UNIQUE INDEX PARTYRSK.XCUST01 ON PARTYRSK.CUSTOMER (CUST_ID ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4 CLUSTER;

CREATE INDEX PARTYRSK.XCUST02 ON PARTYRSK.CUSTOMER (PARTY_ID ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4;

CREATE INDEX PARTYRSK.XCUST03 ON PARTYRSK.CUSTOMER
    (LAST_NAME ASC, FIRST_NAME ASC, DOB ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4;

CREATE INDEX PARTYRSK.XCUST04 ON PARTYRSK.CUSTOMER (NATIONAL_ID ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4;

CREATE UNIQUE INDEX PARTYRSK.XKYC01 ON PARTYRSK.PARTY_KYC
    (PARTY_ID ASC, KYC_SEQ DESC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4 CLUSTER;

CREATE INDEX PARTYRSK.XKYC02 ON PARTYRSK.PARTY_KYC
    (NEXT_REVIEW_DATE ASC, KYC_STATUS ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4;

CREATE UNIQUE INDEX PARTYRSK.XSANC01 ON PARTYRSK.PARTY_SANCTION
    (LIST_CD ASC, ENTRY_ID ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4 CLUSTER;

CREATE INDEX PARTYRSK.XSANC02 ON PARTYRSK.PARTY_SANCTION
    (ENTITY_NAME ASC, ACTIVE_FLG ASC)
    USING STOGROUP SGPARTY PRIQTY 720 SECQTY 360 BUFFERPOOL BP4;

CREATE UNIQUE INDEX PARTYRSK.XEXPO01 ON PARTYRSK.PARTY_EXPOSURE
    (PARTY_ID ASC, AS_OF_DATE DESC, PROD_SYSTEM ASC, PRODUCT_CD ASC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4 CLUSTER;

CREATE INDEX PARTYRSK.XEXPO02 ON PARTYRSK.PARTY_EXPOSURE
    (AS_OF_DATE ASC, STALE_FLG ASC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4;

CREATE UNIQUE INDEX PARTYRSK.XSCORE01 ON PARTYRSK.PARTY_RISK_SCORE
    (PARTY_ID ASC, SCORE_TS DESC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4 CLUSTER;

CREATE INDEX PARTYRSK.XSCORE02 ON PARTYRSK.PARTY_RISK_SCORE
    (RISK_BAND ASC, SCORE_TS DESC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4;

CREATE UNIQUE INDEX PARTYRSK.XRAUD01 ON PARTYRSK.PARTY_RISK_AUDIT
    (AUDIT_ID ASC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4;

CREATE INDEX PARTYRSK.XRAUD02 ON PARTYRSK.PARTY_RISK_AUDIT
    (PARTY_ID ASC, EVENT_TS DESC)
    USING STOGROUP SGPARTY PRIQTY 1440 SECQTY 720 BUFFERPOOL BP4 CLUSTER;
