-- ---------------------------------------------------------------------
-- REFERENTIAL CONSTRAINTS
--
-- NOTE - RELATIONSHIPS THAT SPAN CARDDB AND PARTYDB ARE *NOT* DECLARED.
-- ACCOUNT.PARTY_ID AND ACCOUNT.CUST_ID POINT AT PARTYRSK DATA BUT ARE
-- ENFORCED IN APPLICATION CODE ONLY, BECAUSE THE TWO DATABASES ARE
-- ADMINISTERED SEPARATELY AND UNLOADED ON DIFFERENT SCHEDULES.
-- ---------------------------------------------------------------------

-- CARDDB --------------------------------------------------------------
ALTER TABLE CARDSVC.CARD
    ADD CONSTRAINT FK_CARD_ACCT
    FOREIGN KEY (ACCT_ID) REFERENCES CARDSVC.ACCOUNT (ACCT_ID)
    ON DELETE RESTRICT;

ALTER TABLE CARDSVC.CARD_LIMIT
    ADD CONSTRAINT FK_LIMIT_CARD
    FOREIGN KEY (CARD_NUM) REFERENCES CARDSVC.CARD (CARD_NUM)
    ON DELETE CASCADE;

ALTER TABLE CARDSVC.AUTHORIZATION
    ADD CONSTRAINT FK_AUTH_CARD
    FOREIGN KEY (CARD_NUM) REFERENCES CARDSVC.CARD (CARD_NUM)
    ON DELETE RESTRICT;

ALTER TABLE CARDSVC.TRANSACTION
    ADD CONSTRAINT FK_TXN_ACCT
    FOREIGN KEY (ACCT_ID) REFERENCES CARDSVC.ACCOUNT (ACCT_ID)
    ON DELETE RESTRICT;

ALTER TABLE CARDSVC.DISPUTE
    ADD CONSTRAINT FK_DISP_ACCT
    FOREIGN KEY (ACCT_ID) REFERENCES CARDSVC.ACCOUNT (ACCT_ID)
    ON DELETE RESTRICT;

ALTER TABLE CARDSVC.REWARDS
    ADD CONSTRAINT FK_RWRD_ACCT
    FOREIGN KEY (ACCT_ID) REFERENCES CARDSVC.ACCOUNT (ACCT_ID)
    ON DELETE CASCADE;

ALTER TABLE CARDSVC.STATEMENT
    ADD CONSTRAINT FK_STMT_ACCT
    FOREIGN KEY (ACCT_ID) REFERENCES CARDSVC.ACCOUNT (ACCT_ID)
    ON DELETE RESTRICT;

-- PARTYDB -------------------------------------------------------------
-- PARTY_KYC IS KEYED ON PARTY_ID, BUT CUSTOMER IS KEYED ON CUST_ID AND
-- ONE PARTY MAY HOLD SEVERAL CUSTOMER NUMBERS ACROSS PRODUCT SYSTEMS,
-- SO PARTY_ID IS NOT UNIQUE ON CUSTOMER AND NO CONSTRAINT IS DECLARED.
-- THE RELATIONSHIP IS ENFORCED BY PRKYC01 AND THE PARTYWK LOAD JOBS.

-- PARTY_EXPOSURE AND PARTY_RISK_SCORE ARE DELIBERATELY UNCONSTRAINED.
-- BOTH ARE LOADED BY BATCH FOR PARTIES THAT MAY NOT YET EXIST ON
-- CUSTOMER WHEN THE WEEKLY FEED ARRIVES.
