-- ---------------------------------------------------------------------
-- GRANTS
--
-- CARDSVC AND PARTYRSK RUN UNDER SEPARATE RACF GROUPS AND BIND INTO
-- SEPARATE COLLECTIONS.  CARDSVC HAS NO DIRECT ACCESS TO PARTYDB
-- TABLES EXCEPT THE TWO READ ONLY GRANTS AT THE BOTTOM, WHICH EXIST
-- FOR HISTORICAL REASONS.
-- ---------------------------------------------------------------------

-- Collections ---------------------------------------------------------
GRANT CREATE IN COLLECTION CARDCOLL TO CARDADM;
GRANT CREATE IN COLLECTION PRTYCOLL TO PRTYADM;

GRANT EXECUTE ON PACKAGE CARDCOLL.* TO CARDONL, CARDBAT;
GRANT EXECUTE ON PACKAGE PRTYCOLL.* TO PRTYONL, PRTYBAT, CARDONL, CARDBAT;

-- Plans ---------------------------------------------------------------
GRANT EXECUTE ON PLAN CARDONLP TO CICSCARD;
GRANT EXECUTE ON PLAN CARDNITP TO CARDBAT;
GRANT EXECUTE ON PLAN CARDBILP TO CARDBAT;
GRANT EXECUTE ON PLAN CARDREFP TO CARDBAT;
GRANT EXECUTE ON PLAN PARTYWKP TO PRTYBAT;

-- CARDDB --------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON CARDSVC.ACCOUNT       TO CARDONL, CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.CARD          TO CARDONL, CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.CARD_LIMIT    TO CARDONL, CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.AUTHORIZATION TO CARDONL, CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.TRANSACTION   TO CARDONL, CARDBAT;
GRANT SELECT                  ON CARDSVC.MERCHANT     TO CARDONL, CARDBAT;
GRANT SELECT                  ON CARDSVC.FEE_SCHEDULE TO CARDONL, CARDBAT;
GRANT SELECT                  ON CARDSVC.FRAUD_RULE   TO CARDONL, CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.REWARDS       TO CARDBAT;
GRANT SELECT, INSERT          ON CARDSVC.GL_POSTING   TO CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.STATEMENT     TO CARDBAT;
GRANT SELECT, INSERT, UPDATE ON CARDSVC.DISPUTE       TO CARDONL;
GRANT SELECT                  ON CARDSVC.PGM_ROUTE    TO CARDONL, CARDBAT,
                                                         PRTYONL, PRTYBAT;
GRANT INSERT                  ON CARDSVC.ROUTE_AUDIT  TO CARDONL, CARDBAT;

-- PARTYDB -------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON PARTYRSK.CUSTOMER         TO PRTYONL, PRTYBAT;
GRANT SELECT, INSERT, UPDATE ON PARTYRSK.PARTY_KYC        TO PRTYONL, PRTYBAT;
GRANT SELECT, INSERT, UPDATE ON PARTYRSK.PARTY_SANCTION   TO PRTYONL, PRTYBAT;
GRANT SELECT, INSERT, UPDATE ON PARTYRSK.PARTY_EXPOSURE   TO PRTYONL, PRTYBAT;
GRANT SELECT, INSERT          ON PARTYRSK.PARTY_RISK_SCORE TO PRTYONL, PRTYBAT;
GRANT INSERT                  ON PARTYRSK.PARTY_RISK_AUDIT TO PRTYONL, PRTYBAT;

-- ---------------------------------------------------------------------
-- LEGACY CROSS DATABASE GRANTS
-- PRRSK02 JOINS CARDSVC.ACCOUNT WHEN AGGREGATING CARD EXPOSURE RATHER
-- THAN WAITING FOR THE NIGHTLY FEED.  ADDED 2017 UNDER CHANGE CR-4471.
-- ---------------------------------------------------------------------
GRANT SELECT ON CARDSVC.ACCOUNT    TO PRTYONL, PRTYBAT;
GRANT SELECT ON CARDSVC.CARD_LIMIT TO PRTYBAT;
