//*
//* CARDDB2L - COMMON STEPLIB CONCATENATION FOR CARDSVC DB2 BATCH.
//*
//* INCLUDED BY EVERY STEP OF THE NIGHTLY CYCLE THAT RUNS UNDER
//* IKJEFT01.  KEEP THE CARD LIBRARIES AHEAD OF THE DB2 LIBRARIES -
//* THE EMERGENCY FIX LIBRARY IS SEARCHED FIRST SO THAT A ONE NIGHT
//* PATCH CAN BE BACKED OUT BY EMPTYING IT.
//*
//* CHANGE CONTROL
//* 1994-04-11 CRD0102 CREATED
//* 2002-06-17 CRD2907 DB2 V7 LIBRARIES
//* 2011-10-02 CRD6688 DB2 V9 LIBRARIES, RUNLIB ADDED FOR DSNTIAR
//*
//STEPLIB  DD DSN=CARD.PROD.FIXLIB,DISP=SHR
//         DD DSN=CARD.PROD.LOADLIB,DISP=SHR
//         DD DSN=CARD.PROD.COMMON.LOADLIB,DISP=SHR
//         DD DSN=DSN910.SDSNLOAD,DISP=SHR
//         DD DSN=DSN910.SDSNEXIT,DISP=SHR
//         DD DSN=DSN910.RUNLIB.LOAD,DISP=SHR
