*----------------------------------------------------------------------
* CSDTDQ - TRANSIENT DATA AND TEMPORARY STORAGE DEFINITIONS
*
* GROUP CARDTDQ.  DFHCSDUP BATCH INPUT.
*
* TWO EXTRAPARTITION QUEUES CARRY THE REGION'S OPERATIONAL OUTPUT.
*
*   CLOG   OPERATIONS LOG.  EVERY DIAGNOSTIC THE ERROR HANDLER
*          FORMATS IS WRITTEN HERE.  READ BY THE OPERATIONS SHIFT
*          REPORT EACH MORNING.
*
*   CAUD   SESSION AUDIT.  SIGN ON, SIGN OFF, OPTION SELECTION AND
*          EVERY MAINTENANCE ACTION.  RETAINED SEVEN YEARS - THE
*          DATASET IS A GDG AND THE PREVIOUS GENERATION IS ARCHIVED
*          BY THE NIGHTLY CYCLE.
*
* BOTH ARE EXTRAPARTITION SO THAT THE OUTPUT SURVIVES A REGION
* FAILURE.  AN INTRAPARTITION QUEUE WOULD BE LOST ON A COLD START,
* WHICH IS NOT ACCEPTABLE FOR THE AUDIT TRAIL.
*----------------------------------------------------------------------
*
DELETE GROUP(CARDTDQ)
*
*----------------------------------------------------------------------
* OPERATIONS LOG
*----------------------------------------------------------------------
DEFINE TDQUEUE(CLOG) GROUP(CARDTDQ)
       DESCRIPTION(CARD SERVICING OPERATIONS LOG)
       TYPE(EXTRA)
       DDNAME(CARDCLOG)
       DSNAME(CARD.PROD.CICS.OPSLOG)
       SYSOUTCLASS(A)
       RECORDSIZE(00133)
       BLOCKSIZE(13300)
       RECORDFORMAT(FIXED)
       BLOCKFORMAT(BLOCKED)
       TYPEFILE(OUTPUT)
       DISPOSITION(MOD)
       OPENTIME(INITIAL)
       PRINTCONTROL(ASA)
*
*----------------------------------------------------------------------
* SESSION AUDIT
*----------------------------------------------------------------------
DEFINE TDQUEUE(CAUD) GROUP(CARDTDQ)
       DESCRIPTION(CARD SERVICING SESSION AUDIT TRAIL)
       TYPE(EXTRA)
       DDNAME(CARDCAUD)
       DSNAME(CARD.PROD.CICS.AUDIT(+0))
       RECORDSIZE(00200)
       BLOCKSIZE(20000)
       RECORDFORMAT(FIXED)
       BLOCKFORMAT(BLOCKED)
       TYPEFILE(OUTPUT)
       DISPOSITION(SHR)
       OPENTIME(INITIAL)
*
*----------------------------------------------------------------------
* INTRAPARTITION QUEUE FOR THE DEFERRED WORK TRIGGER
* WHEN AN AUTHORISATION IS REFERRED, THE REFERRAL IS QUEUED HERE AND
* THE TRIGGER LEVEL STARTS THE SERVICING TRANSACTION TO PICK IT UP.
*----------------------------------------------------------------------
DEFINE TDQUEUE(CREF) GROUP(CARDTDQ)
       DESCRIPTION(REFERRED AUTHORISATION WORK QUEUE)
       TYPE(INTRA)
       ATIFACILITY(FILE)
       TRANSID(CA00)
       TRIGGERLEVEL(00001)
       RECOVSTATUS(LOGICAL)
       FACILITYID()
       WAIT(YES)
       WAITACTION(REJECT)
*
*----------------------------------------------------------------------
* TEMPORARY STORAGE MODEL
* THE DISPATCHER CACHES THE RESOLVED ROUTE SET IN A MAIN TEMPORARY
* STORAGE QUEUE PREFIXED CARDRT SO IT IS NOT RE-READ ON EVERY
* DISPATCH IN A PSEUDO CONVERSATION.  MAIN, NOT AUXILIARY - THE
* QUEUE IS SHORT LIVED AND MUST NOT SURVIVE A RESTART.
*----------------------------------------------------------------------
DEFINE TSMODEL(CARDRTQ) GROUP(CARDTDQ)
       DESCRIPTION(DISPATCHER ROUTE CACHE - MAIN, NON RECOVERABLE)
       PREFIX(CARDRT)
       LOCATION(MAIN)
       RECOVERY(NO)
       SECURITY(NO)
*
DEFINE TSMODEL(CARDBRQ) GROUP(CARDTDQ)
       DESCRIPTION(BROWSE PAGE HOLD AREAS - AUXILIARY)
       PREFIX(CARDBR)
       LOCATION(AUXILIARY)
       RECOVERY(NO)
       SECURITY(NO)
       EXPIRYINT(0030)
