"""Generate DCLGEN-shaped COBOL members from the pinned Db2 DDL.

The mappings follow IBM Db2 DCLGEN host-variable conventions documented in the
Db2 for z/OS SQL reference, "Host variables in COBOL":
https://www.ibm.com/docs/en/db2-for-zos/12.0.0?topic=languages-host-variables-in-cobol
CHAR/VARCHAR, integer, decimal, date/time, and floating-point SQL types are
mapped to their documented COBOL PIC/USAGE representations; unsupported types
are rejected instead of being guessed.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DDL_DIR = ROOT / "legacy/db2/mainframe-db2-setup/ddl"
OUTPUT_DIR = ROOT / "artifacts/generated/dclgen"
PIN = "d1450ca062445a6e70f2a2638af6ba286ca8fecc"


@dataclass(frozen=True)
class Column:
    name: str
    sql_type: str
    nullable: bool


TYPE_RE = re.compile(
    r"^(?P<type>[A-Z]+(?:\s*\(\s*\d+\s*(?:,\s*\d+)?\s*\))?)(?P<rest>.*)$",
    re.IGNORECASE,
)
TABLE_RE = re.compile(
    r"CREATE\s+TABLE\s+TRADE\.(?P<table>[A-Z0-9_]+)\s*"
    r"\((?P<columns>.*?)\)\s*IN\b",
    re.IGNORECASE | re.DOTALL,
)


def parse_ddl(path: Path) -> tuple[str, list[Column]] | None:
    text = path.read_text(errors="replace")
    match = TABLE_RE.search(text)
    if not match:
        return None
    columns: list[Column] = []
    for raw_line in match.group("columns").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        line = line.lstrip(",").strip()
        column_match = re.match(r"^(?P<name>[A-Z][A-Z0-9_]*)\s+(?P<definition>.+)$", line, re.I)
        if not column_match:
            raise ValueError(f"{path.name}: cannot parse column line: {raw_line.strip()}")
        type_match = TYPE_RE.match(column_match.group("definition").strip())
        if not type_match:
            raise ValueError(f"{path.name}: cannot parse SQL type: {raw_line.strip()}")
        sql_type = re.sub(r"\s+", "", type_match.group("type").upper())
        rest = type_match.group("rest").upper()
        nullable = "NOT NULL" not in rest
        columns.append(Column(column_match.group("name").upper(), sql_type, nullable))
    return match.group("table").upper(), columns


def _decimal_picture(precision: int, scale: int) -> str:
    if scale == 0:
        return f"S9({precision}) COMP-3"
    if scale == precision:
        return f"SV9({scale}) COMP-3"
    return f"S9({precision - scale})V9({scale}) COMP-3"


def cobol_items(column: Column) -> list[str]:
    match = re.fullmatch(r"([A-Z]+)(?:\((\d+)(?:,(\d+))?\))?", column.sql_type)
    if not match:
        raise ValueError(f"unsupported SQL type {column.sql_type} for {column.name}")
    kind, first, second = match.groups()
    if kind == "CHAR" and first:
        items = [f"10 {column.name.replace('_', '-')} PIC X({first})."]
    elif kind == "VARCHAR" and first:
        name = column.name.replace("_", "-")
        items = [f"10 {name}.", f"49 {name}-LEN PIC S9(4) COMP.", f"49 {name}-TEXT PIC X({first})."]
    elif kind == "SMALLINT":
        items = [f"10 {column.name.replace('_', '-')} PIC S9(4) COMP."]
    elif kind in {"INTEGER", "INT"}:
        items = [f"10 {column.name.replace('_', '-')} PIC S9(9) COMP."]
    elif kind == "BIGINT":
        items = [f"10 {column.name.replace('_', '-')} PIC S9(18) COMP."]
    elif kind in {"DECIMAL", "NUMERIC"} and first:
        scale = int(second or 0)
        items = [f"10 {column.name.replace('_', '-')} PIC {_decimal_picture(int(first), scale)}."]
    elif kind == "DATE":
        items = [f"10 {column.name.replace('_', '-')} PIC X(10)."]
    elif kind == "TIME":
        items = [f"10 {column.name.replace('_', '-')} PIC X(8)."]
    elif kind == "TIMESTAMP":
        items = [f"10 {column.name.replace('_', '-')} PIC X(26)."]
    elif kind == "FLOAT" or kind == "REAL":
        items = [f"10 {column.name.replace('_', '-')} COMP-1."]
    elif kind == "DOUBLE":
        items = [f"10 {column.name.replace('_', '-')} COMP-2."]
    else:
        raise ValueError(f"unsupported SQL type {column.sql_type} for {column.name}")
    if column.nullable:
        items.append(f"10 {column.name.replace('_', '-')}-NULL PIC S9(4) COMP.")
    return items


def fixed_line(sequence: int, content: str = "") -> str:
    if len(content) > 65:
        raise ValueError(f"DCLGEN content exceeds area B: {content}")
    return f"{sequence:06d} {content:<65}{sequence % 100000000:08d}"


def render_member(table: str, columns: list[Column]) -> str:
    lines = [
        "* Generated by tools/dclgen.py from pinned estate DDL.",
        f"* Estate pin: {PIN}.",
        "* Upstream DCLGEN PDS ships no members.",
        "* Confirm generated members against the customer DCLGEN PDS.",
        "       EXEC SQL",
        f"          DECLARE TRADE.{table} TABLE",
        "          (",
    ]
    for index, column in enumerate(columns):
        suffix = "," if index < len(columns) - 1 else ""
        lines.append(f"             {column.name} {column.sql_type}{' NOT NULL' if not column.nullable else ''}{suffix}")
    lines.extend(["          )", "       END-EXEC.", f"       01 DCL{table}."])
    for column in columns:
        lines.extend(f"          {item}" for item in cobol_items(column))
    return "\n".join(fixed_line((index + 1) * 100, line) for index, line in enumerate(lines)) + "\n"


def generate() -> list[Path]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []
    for path in sorted(DDL_DIR.iterdir()):
        if path.name.startswith("#"):
            continue
        parsed = parse_ddl(path)
        if parsed is None:
            continue
        table, columns = parsed
        output = OUTPUT_DIR / f"DCL{table}"
        output.write_text(render_member(table, columns))
        generated.append(output)
    if not generated:
        raise RuntimeError(f"no CREATE TABLE TRADE definitions found under {DDL_DIR}")
    return generated


if __name__ == "__main__":
    files = generate()
    print(f"DCLGEN PASS: generated {len(files)} members under {OUTPUT_DIR}")
